version: '3.9'

services:
  django:
    image: docker:0.0.1
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db



  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: '127.0.0.1'
      MYSQL_PORT: '3306'
      MYSQL_DATABASE: 'restjwt'
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db/mysql/db:/var/lib/mysql
    ports:
      - "3308:3306"