version: '3.9'

services:
  django:
    image: docker:0.0.1
    build: .
    restart: always
    volumes:
      - .:/code
    # command: sh -c "sleep 10s ;"
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - "8000:8000"
    # links: 
    #   - mysql:mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: rj
      MYSQL_USER: user
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE_PORT: 3306
      # MYSQL_HOST:
    depends_on:
      - db



  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # MYSQL_HOST: "127.0.0.1"
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: rj
      MYSQL_USER: user
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE_PORT: 3306
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      # MYSQL_ROOT_HOST: "%"
    volumes:
      - ./db:/var/lib/mysql
      # - ./db/mysql/db:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  db: